# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3a78f085757962a99a4d5048f01a8d7f56a1225d806aa1dccdf8d7ad098a0b420494ad25d06fd294bcd075c076a7d0bd3a2d35bbd71ddb0b6cc4825f3e12875c

test:
  secret_key_base: 0bc06ee78170ff45d96f4ecbc8c8e3a0caf090fbd13d36527ba17647abd28fedfe24eeeff6b16ca65da52bce28d261fab7029b69f4e83c9880e4e0e90e629378

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
